name = "H5Sparse"
uuid = "d026d0c0-3790-4945-99de-4163f1ba8085"
authors = ["Albin Severinson <albin@severinson.org> and contributors"]
version = "0.3.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
HDF5 = "0.15"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
